// sql/dump.js — export the seeded data to a file that can be committed.
//
//   node sql/dump.js
//
// Writes backend/sql/data/seed_data.sql. Run this ONCE on the machine that has a
// fully seeded database, then commit the file. Everybody else runs
// `npm run db:restore` and gets the same catalogue in seconds — no internet, no
// waiting on Jikan's rate limit, no "works on my machine".
//
// Why --inserts instead of the default COPY format: plain INSERT statements can
// be executed by the `pg` driver directly, so restoring needs nothing but Node.
// COPY ... FROM stdin would require the psql client on every machine.
//
// User data (users, watchlist, reviews, votes, follows, notifications, activity)
// is deliberately excluded — it contains password hashes and is personal to
// whoever seeded it. Only the public anime catalogue is shared.
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");
require("dotenv").config({ path: path.join(__dirname, "..", ".env") });

const CATALOGUE_TABLES = [
  "anime",
  "genres",
  "studios",
  "anime_genres",
  "anime_studios",
  "episodes",
];

const OUT_DIR = path.join(__dirname, "data");
const OUT_FILE = path.join(OUT_DIR, "seed_data.sql");

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is not set. Create backend/.env first.");
  process.exit(1);
}

const args = [
  process.env.DATABASE_URL,
  "--data-only",
  "--inserts",
  "--no-owner",
  "--no-privileges",
  ...CATALOGUE_TABLES.flatMap((t) => ["--table", t]),
];

console.log("Dumping catalogue tables:", CATALOGUE_TABLES.join(", "));

const res = spawnSync("pg_dump", args, { encoding: "utf8", maxBuffer: 512 * 1024 * 1024 });

if (res.error && res.error.code === "ENOENT") {
  console.error(
    "\npg_dump not found on this machine.\n" +
      "It ships with the PostgreSQL client tools:\n" +
      "  Ubuntu/Debian : sudo apt install postgresql-client\n" +
      "  macOS         : brew install libpq && brew link --force libpq\n" +
      "  Windows       : included with the PostgreSQL installer\n\n" +
      "Only the person creating the dump needs it. Everyone else just runs db:restore."
  );
  process.exit(1);
}

if (res.status !== 0) {
  console.error("pg_dump failed:\n" + (res.stderr || "").trim());
  process.exit(1);
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const header = `-- seed_data.sql — generated by \`npm run db:dump\` on ${new Date().toISOString()}
--
-- Catalogue data only (anime, genres, studios, bridges, episodes).
-- No user data, no password hashes.
--
-- Restore with:  npm run db:restore     (after npm run db:setup)
-- Regenerate with: npm run db:dump
--
`;

fs.writeFileSync(OUT_FILE, header + res.stdout, "utf8");

const kb = Math.round(fs.statSync(OUT_FILE).size / 1024);
const inserts = (res.stdout.match(/^INSERT INTO/gm) || []).length;

console.log(`\nWrote ${path.relative(path.join(__dirname, "..", ".."), OUT_FILE)}`);
console.log(`  ${inserts} INSERT statements, ${kb} KB`);
console.log("\nCommit this file so teammates can run: npm run db:restore");
